sudo: false

language: node_js

node_js:
  - node

env:
  - PORT=4000
  - NODE_ENV=test

before_script:
  - cp ormconfig.example.json ormconfig.json

script:
  - npm run lint
  - npm run test:coveralls  